site_name: My blog
site_url: https://blog.ramseskools.nl
repo_url: https://github.com/RamsesKools/my-blog

theme:
  name: material
  font: false
  logo: assets/logo-rk.svg
  favicon: assets/favicon.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: custom
    accent: custom
  features:
    - navigation.tabs

plugins:
  - blog:
      blog_dir: .
      draft_on_serve: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
extra_css:
  - assets/custom.css

nav:
  - Blog: index.md
  - About: about.md
